CREATE OR REPLACE DATABASE "FILE_LOADER_MASTER_DB";

CREATE SCHEMA "FILE_LOADER_MASTER_DB"."ELT";

CREATE OR REPLACE TABLE "FILE_LOADER_MASTER_DB"."ELT"."FL_LOG" (
	STEP_GROUP VARCHAR(128)
    ,STEP VARCHAR(128)
    ,TS DATETIME
);

CREATE OR REPLACE TABLE "FILE_LOADER_MASTER_DB"."ELT"."FL_ERROR_LOG" (
    STEP_GROUP VARCHAR(128)
    ,STEP VARCHAR(128)
    ,ERROR_MESSAGE VARCHAR(128)
    ,TS DATETIME
);
